---
- name: check iptables version
  shell: iptables --version
  register: iptables_version
  changed_when: false

- block:
    - alternatives:
        name: iptables
        path: /usr/sbin/iptables-legacy

    - alternatives:
        name: ip6tables
        path: /usr/sbin/ip6tables-legacy

  when: '"nf_tables" in iptables_version.stdout'
